// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPlwS-eYBFoHa0K_fIqr-qA2AoxWSXENs',
    appId: '1:56104389901:web:4eaa316d038295230b3444',
    messagingSenderId: '56104389901',
    projectId: 'eduhelix-db',
    authDomain: 'eduhelix-db.firebaseapp.com',
    storageBucket: 'eduhelix-db.appspot.com',
    measurementId: 'G-85CFJLJT3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBZ0_7zoxo5fGgAtGavbwF5TnEJIXdnHY',
    appId: '1:56104389901:android:09a85e2287f220740b3444',
    messagingSenderId: '56104389901',
    projectId: 'eduhelix-db',
    storageBucket: 'eduhelix-db.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPlwS-eYBFoHa0K_fIqr-qA2AoxWSXENs',
    appId: '1:56104389901:web:2dbf27e72270a17d0b3444',
    messagingSenderId: '56104389901',
    projectId: 'eduhelix-db',
    authDomain: 'eduhelix-db.firebaseapp.com',
    storageBucket: 'eduhelix-db.appspot.com',
    measurementId: 'G-QGGHRX1Z1T',
  );
}
