// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_u08UAnhQFTBmTv33HifWkJuCUkRp9MU',
    appId: '1:325108867243:web:5ea84d49d31515bc5cd7ee',
    messagingSenderId: '325108867243',
    projectId: 'tourista-db',
    authDomain: 'tourista-db.firebaseapp.com',
    storageBucket: 'tourista-db.firebasestorage.app',
    measurementId: 'G-B5MTTL54YL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSjlfedE5YwY2HzZK34jRlRumtt0Pfv8k',
    appId: '1:325108867243:android:590f1696a52ad6eb5cd7ee',
    messagingSenderId: '325108867243',
    projectId: 'tourista-db',
    storageBucket: 'tourista-db.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_u08UAnhQFTBmTv33HifWkJuCUkRp9MU',
    appId: '1:325108867243:web:1750c80c2441646c5cd7ee',
    messagingSenderId: '325108867243',
    projectId: 'tourista-db',
    authDomain: 'tourista-db.firebaseapp.com',
    storageBucket: 'tourista-db.firebasestorage.app',
    measurementId: 'G-XDQZLWYMRV',
  );
}
